import type { SupportedLocale } from "@shared/localization";

const copy = {
  en: {
    allSuccessFees: "All success fees", showingNewestFees: "Showing the newest 100 of {count} success fees.", user: "User", employerRole: "Employer / role", salary: "Salary", monthlyFee: "Monthly fee", status: "Status", nextVerification: "Next verification", actions: "Actions", unknown: "Unknown", perMonth: "per month", changeStatus: "Change status", escalate: "Escalate", note: "Note", noSuccessFees: "No success fees found.",
    overdueVerifications: "Overdue verifications", showingOldestOverdue: "Showing the 100 oldest of {count} overdue records.", daysOverdue: "Days overdue", graceExpired: "Grace expired", daysCount: "{count} days", suspendRequired: "Yes - suspend", withinGrace: "No - within grace", suspend: "Suspend", noOverdue: "No overdue verifications.", autoSuspendedNote: "Suspended after employment verification became {count} days overdue.",
    pendingVerificationReviews: "Pending verification reviews", showingNewestVerifications: "Showing the newest 100 of {count} pending verifications.", submittedSalary: "Submitted: {date} | Salary: {salary} per month", viewDocument: "View document", approve: "Approve", reject: "Reject", rejectionEvidenceNote: "Document insufficient or invalid", noPendingVerifications: "No pending verifications.",
    operatingReviewQueue: "Operating review queue", showingNewestReviews: "Showing the newest 100 of {count} open reviews.", entityReference: "{entity} #{id}", manualDecision: "Manual decision", userCreated: "User #{userId} | Created {date}", evidence: "Evidence", recordReview: "Record review", resolve: "Resolve", closeRequest: "Close request", dismiss: "Dismiss", noOpenReviews: "No open review items.",
    paymentHistory: "Payment history", showingNewestPayments: "Showing the newest 50 of {count} payments.", employer: "Employer", amount: "Amount", period: "Period", paidAt: "Paid at", noPayments: "No payments recorded yet.",
    updateFeeStatus: "Update fee status", newStatus: "New status", optionalNote: "Note (optional)", statusReasonPlaceholder: "Reason for status change...", cancel: "Cancel", updateStatus: "Update status",
    legalEscalation: "Flag for legal escalation", legalEscalationDetail: "This marks {name}'s account as disputed and suspends it. The action is audited and can only be reversed through manual review.", escalationReason: "Reason for escalation", escalationPlaceholder: "Describe the non-compliance or reason for legal escalation...", confirmEscalation: "Confirm escalation",
    addAdminNote: "Add admin note", adminNote: "Note", adminNotePlaceholder: "Add an internal note...", saveNote: "Save note",
    recordPrivacyReview: "Record privacy review", closePrivacyRequest: "Close privacy request", resolveReviewItem: "Resolve review item", dismissReviewItem: "Dismiss review item", privacyPlanningNotice: "A resolved decision records an itemized, restart-safe execution plan. Planning does not delete account data, revoke providers, or override an active legal hold.", resolutionNote: "Resolution note", privacyResolutionPlaceholder: "Record the retention basis, data eligible for erasure, and the separate execution work required...", reviewResolutionPlaceholder: "Describe what was reviewed and why this item can be closed...", recordAndPlan: "Record and plan",
    feeStatusUpdated: "Fee status updated", verificationApproved: "Verification approved", verificationRejected: "Verification rejected", legalEscalationRecorded: "Account flagged for legal escalation", noteAdded: "Note added", userReinstated: "User reinstated", invalidDownloadUrl: "The verification download URL is invalid.", downloadFailed: "Could not open the verification document",
    active: "Active", pending_verification: "Pending verification", suspended: "Suspended", disputed: "Disputed", ended: "Ended", paused: "Paused", pending: "Pending", approved: "Approved", rejected: "Rejected", paid: "Paid", failed: "Failed", open: "Open", in_progress: "In progress", resolved: "Resolved", dismissed: "Dismissed", low: "Low", medium: "Medium", high: "High", critical: "Critical", initial: "Initial", other: "Other",
  },
  nl: {
    allSuccessFees: "Alle succesvergoedingen", showingNewestFees: "De nieuwste 100 van {count} succesvergoedingen worden getoond.", user: "Gebruiker", employerRole: "Werkgever / functie", salary: "Salaris", monthlyFee: "Maandelijkse vergoeding", status: "Status", nextVerification: "Volgende verificatie", actions: "Acties", unknown: "Onbekend", perMonth: "per maand", changeStatus: "Status wijzigen", escalate: "Escaleren", note: "Notitie", noSuccessFees: "Geen succesvergoedingen gevonden.",
    overdueVerifications: "Te late verificaties", showingOldestOverdue: "De 100 oudste van {count} te late registraties worden getoond.", daysOverdue: "Dagen te laat", graceExpired: "Respijttermijn verstreken", daysCount: "{count} dagen", suspendRequired: "Ja - opschorten", withinGrace: "Nee - binnen respijttermijn", suspend: "Opschorten", noOverdue: "Geen te late verificaties.", autoSuspendedNote: "Opgeschort nadat de arbeidsverificatie {count} dagen te laat werd.",
    pendingVerificationReviews: "Openstaande verificatiebeoordelingen", showingNewestVerifications: "De nieuwste 100 van {count} openstaande verificaties worden getoond.", submittedSalary: "Ingediend: {date} | Salaris: {salary} per maand", viewDocument: "Document bekijken", approve: "Goedkeuren", reject: "Afwijzen", rejectionEvidenceNote: "Document is onvoldoende of ongeldig", noPendingVerifications: "Geen openstaande verificaties.",
    operatingReviewQueue: "Operationele beoordelingswachtrij", showingNewestReviews: "De nieuwste 100 van {count} open beoordelingen worden getoond.", entityReference: "{entity} #{id}", manualDecision: "Handmatig besluit", userCreated: "Gebruiker #{userId} | Aangemaakt {date}", evidence: "Bewijs", recordReview: "Beoordeling vastleggen", resolve: "Oplossen", closeRequest: "Verzoek sluiten", dismiss: "Afwijzen", noOpenReviews: "Geen open beoordelingspunten.",
    paymentHistory: "Betalingsgeschiedenis", showingNewestPayments: "De nieuwste 50 van {count} betalingen worden getoond.", employer: "Werkgever", amount: "Bedrag", period: "Periode", paidAt: "Betaald op", noPayments: "Nog geen betalingen vastgelegd.",
    updateFeeStatus: "Status van vergoeding wijzigen", newStatus: "Nieuwe status", optionalNote: "Notitie (optioneel)", statusReasonPlaceholder: "Reden voor de statuswijziging...", cancel: "Annuleren", updateStatus: "Status wijzigen",
    legalEscalation: "Markeren voor juridische escalatie", legalEscalationDetail: "Hiermee wordt het account van {name} als betwist gemarkeerd en opgeschort. De actie wordt gecontroleerd vastgelegd en kan alleen na handmatige beoordeling worden teruggedraaid.", escalationReason: "Reden voor escalatie", escalationPlaceholder: "Beschrijf de niet-naleving of reden voor juridische escalatie...", confirmEscalation: "Escalatie bevestigen",
    addAdminNote: "Beheernotitie toevoegen", adminNote: "Notitie", adminNotePlaceholder: "Voeg een interne notitie toe...", saveNote: "Notitie opslaan",
    recordPrivacyReview: "Privacybeoordeling vastleggen", closePrivacyRequest: "Privacyverzoek sluiten", resolveReviewItem: "Beoordelingspunt oplossen", dismissReviewItem: "Beoordelingspunt afwijzen", privacyPlanningNotice: "Een opgelost besluit legt een gespecificeerd, herstartbestendig uitvoeringsplan vast. Planning verwijdert geen accountgegevens, trekt geen providertoegang in en omzeilt geen actieve juridische bewaarplicht.", resolutionNote: "Besluitnotitie", privacyResolutionPlaceholder: "Leg de bewaarbasis, gegevens die mogen worden gewist en het afzonderlijke vereiste uitvoeringswerk vast...", reviewResolutionPlaceholder: "Beschrijf wat is beoordeeld en waarom dit punt kan worden gesloten...", recordAndPlan: "Vastleggen en plannen",
    feeStatusUpdated: "Status van vergoeding bijgewerkt", verificationApproved: "Verificatie goedgekeurd", verificationRejected: "Verificatie afgewezen", legalEscalationRecorded: "Account gemarkeerd voor juridische escalatie", noteAdded: "Notitie toegevoegd", userReinstated: "Gebruiker hersteld", invalidDownloadUrl: "De download-URL voor verificatie is ongeldig.", downloadFailed: "Het verificatiedocument kon niet worden geopend",
    active: "Actief", pending_verification: "Openstaande verificatie", suspended: "Opgeschort", disputed: "Betwist", ended: "Beeindigd", paused: "Gepauzeerd", pending: "Openstaand", approved: "Goedgekeurd", rejected: "Afgewezen", paid: "Betaald", failed: "Mislukt", open: "Open", in_progress: "In behandeling", resolved: "Opgelost", dismissed: "Afgewezen", low: "Laag", medium: "Gemiddeld", high: "Hoog", critical: "Kritiek", initial: "Initieel", other: "Overig",
  },
} as const satisfies Record<SupportedLocale, Record<string, string>>;

export type AdminFinancialCopyKey = keyof typeof copy.en;

export function getAdminFinancialCopy(locale: SupportedLocale, key: AdminFinancialCopyKey) {
  return copy[locale][key];
}

export function formatAdminFinancialCopy(locale: SupportedLocale, key: AdminFinancialCopyKey, values: Record<string, string | number>) {
  return Object.entries(values).reduce((result, [name, value]) => result.replaceAll(`{${name}}`, String(value)), getAdminFinancialCopy(locale, key) as string);
}

export function getAdminFinancialStatusCopy(locale: SupportedLocale, status: string) {
  return status in copy.en ? copy[locale][status as AdminFinancialCopyKey] : status.replaceAll("_", " ");
}
