import type { SupportedLocale } from "@shared/localization";

const copy = {
  en: {
    allSuccessFees: "All success fees", showingNewestFees: "Showing the newest 100 of {count} success fees.", user: "User", employerRole: "Employer / role", salary: "Salary", monthlyFee: "Monthly fee", status: "Status", nextVerification: "Next verification", actions: "Actions", unknown: "Unknown", perMonth: "per month", changeStatus: "Change status", escalate: "Escalate", note: "Note", noSuccessFees: "No success fees found.",
    overdueVerifications: "Overdue verifications", showingOldestOverdue: "Showing the 100 oldest of {count} overdue records.", daysOverdue: "Days overdue", graceExpired: "Grace expired", daysCount: "{count} days", suspendRequired: "Yes - suspend", withinGrace: "No - within grace", suspend: "Suspend", noOverdue: "No overdue verifications.", autoSuspendedNote: "Suspended after employment verification became {count} days overdue.",
    pendingVerificationReviews: "Pending verification reviews", showingNewestVerifications: "Showing the newest 100 of {count} pending verifications.", submittedSalary: "Submitted: {date} | Salary: {salary} per month", viewDocument: "View document", approve: "Approve", reject: "Reject", rejectionEvidenceNote: "Document insufficient or invalid", noPendingVerifications: "No pending verifications.",
    operatingReviewQueue: "Operating review queue", showingNewestReviews: "Showing the newest 100 of {count} open reviews.", entityReference: "{entity} #{id}", manualDecision: "Manual decision", userCreated: "User #{userId} | Created {date}", evidence: "Evidence", recordReview: "Record review", resolve: "Resolve", closeRequest: "Close request", dismiss: "Dismiss", noOpenReviews: "No open review items.",
    paymentHistory: "Payment history", showingNewestPayments: "Showing the newest 50 of {count} payments.", employer: "Employer", amount: "Amount", period: "Period", paidAt: "Paid at", noPayments: "No payments recorded yet.",
    updateFeeStatus: "Update fee status", newStatus: "New status", optionalNote: "Note (optional)", statusReasonPlaceholder: "Reason for status change...", cancel: "Cancel", updateStatus: "Update status",
    legalEscalation: "Flag for legal escalation", legalEscalationDetail: "This marks {name}'s account as disputed and suspends it. The action is audited and can only be reversed through manual review.", escalationReason: "Reason for escalation", escalationPlaceholder: "Describe the non-compliance or reason for legal escalation...", confirmEscalation: "Confirm escalation",
    addAdminNote: "Add admin note", adminNote: "Note", adminNotePlaceholder: "Add an internal note...", saveNote: "Save note",
    recordPrivacyReview: "Record privacy review", closePrivacyRequest: "Close privacy request", resolveReviewItem: "Resolve review item", dismissReviewItem: "Dismiss review item", privacyPlanningNotice: "A resolved decision records an itemized, restart-safe execution plan. Planning does not delete account data, revoke providers, or override an active legal hold.", resolutionNote: "Resolution note", privacyResolutionPlaceholder: "Record the retention basis, data eligible for erasure, and the separate execution work required...", reviewResolutionPlaceholder: "Describe what was reviewed and why this item can be closed...", recordAndPlan: "Record and plan",
    reviewEvidenceTitle: "Review evidence", loadingLinkedEvidence: "Loading linked evidence...", reviewItem: "Review item", jobSeeker: "Job seeker", unknownUser: "Unknown user", noEmail: "No email", tosAccepted: "ToS accepted", tosMissing: "ToS missing", decision: "Decision", approvals: "Approvals", attempts: "Attempts", responses: "Responses", audit: "Audit", material: "Material",
    retentionPreview: "Retention and erasure preview", readOnlyInventory: "Read-only inventory. Previewing or resolving this review does not delete data.", policyVersion: "Policy {version}", countingRecords: "Counting user-owned records...", erase: "Erase", scrubRetain: "Scrub and retain", legallyRetained: "Legally retained", privateObjectFields: "Private object fields", providerRevocations: "Provider revocations", recordCount: "{count} record(s)", nonDestructivePlan: "Resolving this review creates a non-destructive, itemized execution plan. It does not revoke providers, delete objects, or change user data.", executionPlan: "Execution plan #{id}", itemizedTasks: "{count} itemized task(s)", externalCleanupConfirmation: "External cleanup confirmation", runCleanup: "Run cleanup", manualCleanupEvidence: "Manual {provider} cleanup evidence", confirmProviderRemoval: "Confirm provider removal", externalCleanupComplete: "External cleanup is complete. This final action atomically erases product data, scrubs retained ledgers, pseudonymizes the account, and preserves regulated records.", databaseErasureConfirmation: "Database erasure confirmation", finalizeErasure: "Finalize erasure", erasureCompleted: "Erasure completed. Regulated records remain retained under the recorded policy with the account identity pseudonymized.",
    linkedApplication: "Linked application", applicationNumber: "Application #{id}", unknownCompany: "Unknown company", unknownLocation: "Unknown location", noApplicationNotes: "No application notes recorded.", linkedApplicationMissing: "The review item points to an application record that could not be loaded for the linked user.", decisionPolicy: "Decision and policy", matchPercent: "{count}% match", decisionReason: "Decision reason", noDecisionReason: "No decision reason recorded.", reviewReason: "Review reason", noReviewReason: "No review reason recorded.", decidedBy: "Decided by {actor}. External action remains blocked until the approval gate and evidence checklist are resolved.", noDecision: "No application decision record is linked to this review item yet.",
    materialClaims: "Material and claims", coverLetter: "Cover letter", customAnswers: "Custom answers", supportedClaims: "Supported claims", stored: "Stored", missing: "Missing", noPreparedMaterial: "No prepared material is linked to this review item.", approvalGates: "Approval gates", noApprovalGates: "No approval gates are linked to this entity.", submissionAttempts: "Submission attempts", noSubmissionAttempts: "No submission attempt evidence has been recorded.", employerResponses: "Employer responses", noEmployerResponses: "No employer response is linked to this review item.", auditTrail: "Audit trail ({count})", actorVia: "{actor} via {source}", unknownSource: "unknown source", noAuditEvents: "No audit events are linked to this entity.",
    reviewPlanCreated: "Review recorded and erasure plan #{id} created", reviewItemUpdated: "Review item updated", cleanupFinished: "External cleanup finished with status {status}", manualCleanupRecorded: "Manual provider cleanup evidence recorded", databaseErasureCompleted: "Database erasure completed transactionally",
    application: "Application", success_fee: "Success fee", verification: "Verification",
    feeStatusUpdated: "Fee status updated", verificationApproved: "Verification approved", verificationRejected: "Verification rejected", legalEscalationRecorded: "Account flagged for legal escalation", noteAdded: "Note added", userReinstated: "User reinstated", invalidDownloadUrl: "The verification download URL is invalid.", downloadFailed: "Could not open the verification document",
    active: "Active", pending_verification: "Pending verification", suspended: "Suspended", disputed: "Disputed", ended: "Ended", paused: "Paused", pending: "Pending", approved: "Approved", rejected: "Rejected", paid: "Paid", failed: "Failed", open: "Open", in_progress: "In progress", resolved: "Resolved", dismissed: "Dismissed", low: "Low", medium: "Medium", high: "High", critical: "Critical", initial: "Initial", other: "Other", review: "Review", application_review: "Application review", submission_evidence: "Submission evidence", employer_response: "Employer response", offer_attribution: "Offer attribution", verification_overdue: "Verification overdue", payment_failed: "Payment failed", legal_escalation: "Legal escalation", employment_ended: "Employment ended", privacy_deletion: "Privacy deletion", scrub_and_retain: "Scrub and retain", retain: "Retain", provider_revoke: "Provider revocation", object_delete: "Object deletion", private_object_delete: "Private object deletion", retention_hold: "Retention hold", database_finalize: "Database finalization", prepare: "Preparation", manual_confirmation: "Manual confirmation", external_handoff: "External handoff", planned: "Planned", cleanup_in_progress: "Cleanup in progress", blocked: "Blocked", ready_for_database: "Ready for database", completed: "Completed",
  },
  nl: {
    allSuccessFees: "Alle succesvergoedingen", showingNewestFees: "De nieuwste 100 van {count} succesvergoedingen worden getoond.", user: "Gebruiker", employerRole: "Werkgever / functie", salary: "Salaris", monthlyFee: "Maandelijkse vergoeding", status: "Status", nextVerification: "Volgende verificatie", actions: "Acties", unknown: "Onbekend", perMonth: "per maand", changeStatus: "Status wijzigen", escalate: "Escaleren", note: "Notitie", noSuccessFees: "Geen succesvergoedingen gevonden.",
    overdueVerifications: "Te late verificaties", showingOldestOverdue: "De 100 oudste van {count} te late registraties worden getoond.", daysOverdue: "Dagen te laat", graceExpired: "Respijttermijn verstreken", daysCount: "{count} dagen", suspendRequired: "Ja - opschorten", withinGrace: "Nee - binnen respijttermijn", suspend: "Opschorten", noOverdue: "Geen te late verificaties.", autoSuspendedNote: "Opgeschort nadat de arbeidsverificatie {count} dagen te laat werd.",
    pendingVerificationReviews: "Openstaande verificatiebeoordelingen", showingNewestVerifications: "De nieuwste 100 van {count} openstaande verificaties worden getoond.", submittedSalary: "Ingediend: {date} | Salaris: {salary} per maand", viewDocument: "Document bekijken", approve: "Goedkeuren", reject: "Afwijzen", rejectionEvidenceNote: "Document is onvoldoende of ongeldig", noPendingVerifications: "Geen openstaande verificaties.",
    operatingReviewQueue: "Operationele beoordelingswachtrij", showingNewestReviews: "De nieuwste 100 van {count} open beoordelingen worden getoond.", entityReference: "{entity} #{id}", manualDecision: "Handmatig besluit", userCreated: "Gebruiker #{userId} | Aangemaakt {date}", evidence: "Bewijs", recordReview: "Beoordeling vastleggen", resolve: "Oplossen", closeRequest: "Verzoek sluiten", dismiss: "Afwijzen", noOpenReviews: "Geen open beoordelingspunten.",
    paymentHistory: "Betalingsgeschiedenis", showingNewestPayments: "De nieuwste 50 van {count} betalingen worden getoond.", employer: "Werkgever", amount: "Bedrag", period: "Periode", paidAt: "Betaald op", noPayments: "Nog geen betalingen vastgelegd.",
    updateFeeStatus: "Status van vergoeding wijzigen", newStatus: "Nieuwe status", optionalNote: "Notitie (optioneel)", statusReasonPlaceholder: "Reden voor de statuswijziging...", cancel: "Annuleren", updateStatus: "Status wijzigen",
    legalEscalation: "Markeren voor juridische escalatie", legalEscalationDetail: "Hiermee wordt het account van {name} als betwist gemarkeerd en opgeschort. De actie wordt gecontroleerd vastgelegd en kan alleen na handmatige beoordeling worden teruggedraaid.", escalationReason: "Reden voor escalatie", escalationPlaceholder: "Beschrijf de niet-naleving of reden voor juridische escalatie...", confirmEscalation: "Escalatie bevestigen",
    addAdminNote: "Beheernotitie toevoegen", adminNote: "Notitie", adminNotePlaceholder: "Voeg een interne notitie toe...", saveNote: "Notitie opslaan",
    recordPrivacyReview: "Privacybeoordeling vastleggen", closePrivacyRequest: "Privacyverzoek sluiten", resolveReviewItem: "Beoordelingspunt oplossen", dismissReviewItem: "Beoordelingspunt afwijzen", privacyPlanningNotice: "Een opgelost besluit legt een gespecificeerd, herstartbestendig uitvoeringsplan vast. Planning verwijdert geen accountgegevens, trekt geen providertoegang in en omzeilt geen actieve juridische bewaarplicht.", resolutionNote: "Besluitnotitie", privacyResolutionPlaceholder: "Leg de bewaarbasis, gegevens die mogen worden gewist en het afzonderlijke vereiste uitvoeringswerk vast...", reviewResolutionPlaceholder: "Beschrijf wat is beoordeeld en waarom dit punt kan worden gesloten...", recordAndPlan: "Vastleggen en plannen",
    reviewEvidenceTitle: "Beoordelingsbewijs", loadingLinkedEvidence: "Gekoppeld bewijs laden...", reviewItem: "Beoordelingspunt", jobSeeker: "Werkzoekende", unknownUser: "Onbekende gebruiker", noEmail: "Geen e-mailadres", tosAccepted: "Voorwaarden geaccepteerd", tosMissing: "Voorwaarden ontbreken", decision: "Besluit", approvals: "Goedkeuringen", attempts: "Pogingen", responses: "Reacties", audit: "Controle", material: "Materiaal",
    retentionPreview: "Voorbeeld van bewaring en wissing", readOnlyInventory: "Alleen-lezen inventaris. Het bekijken of oplossen van deze beoordeling verwijdert geen gegevens.", policyVersion: "Beleid {version}", countingRecords: "Registraties van de gebruiker tellen...", erase: "Wissen", scrubRetain: "Opschonen en bewaren", legallyRetained: "Juridisch bewaard", privateObjectFields: "Velden van priveobjecten", providerRevocations: "Intrekkingen bij providers", recordCount: "{count} registratie(s)", nonDestructivePlan: "Het oplossen van deze beoordeling maakt een niet-destructief, gespecificeerd uitvoeringsplan. Providers worden niet ingetrokken, objecten niet verwijderd en gebruikersgegevens niet gewijzigd.", executionPlan: "Uitvoeringsplan #{id}", itemizedTasks: "{count} gespecificeerde taak/taken", externalCleanupConfirmation: "Bevestiging externe opschoning", runCleanup: "Opschoning uitvoeren", manualCleanupEvidence: "Handmatig bewijs voor opschoning bij {provider}", confirmProviderRemoval: "Verwijdering bij provider bevestigen", externalCleanupComplete: "Externe opschoning is voltooid. Deze laatste actie wist productgegevens atomair, schoont bewaarde registers op, pseudonimiseert het account en bewaart gereguleerde registraties.", databaseErasureConfirmation: "Bevestiging databasewissing", finalizeErasure: "Wissing afronden", erasureCompleted: "Wissing voltooid. Gereguleerde registraties blijven onder het vastgelegde beleid bewaard en de accountidentiteit is gepseudonimiseerd.",
    linkedApplication: "Gekoppelde sollicitatie", applicationNumber: "Sollicitatie #{id}", unknownCompany: "Onbekend bedrijf", unknownLocation: "Onbekende locatie", noApplicationNotes: "Geen sollicitatienotities vastgelegd.", linkedApplicationMissing: "Het beoordelingspunt verwijst naar een sollicitatie die niet voor de gekoppelde gebruiker kon worden geladen.", decisionPolicy: "Besluit en beleid", matchPercent: "{count}% match", decisionReason: "Besluitreden", noDecisionReason: "Geen besluitreden vastgelegd.", reviewReason: "Beoordelingsreden", noReviewReason: "Geen beoordelingsreden vastgelegd.", decidedBy: "Besloten door {actor}. Externe actie blijft geblokkeerd totdat de goedkeuringspoort en bewijscontrole zijn afgehandeld.", noDecision: "Er is nog geen sollicitatiebesluit aan dit beoordelingspunt gekoppeld.",
    materialClaims: "Materiaal en beweringen", coverLetter: "Motivatiebrief", customAnswers: "Aangepaste antwoorden", supportedClaims: "Onderbouwde beweringen", stored: "Opgeslagen", missing: "Ontbreekt", noPreparedMaterial: "Er is geen voorbereid materiaal aan dit beoordelingspunt gekoppeld.", approvalGates: "Goedkeuringspoorten", noApprovalGates: "Er zijn geen goedkeuringspoorten aan deze entiteit gekoppeld.", submissionAttempts: "Indieningspogingen", noSubmissionAttempts: "Er is geen bewijs van een indieningspoging vastgelegd.", employerResponses: "Werkgeversreacties", noEmployerResponses: "Er is geen werkgeversreactie aan dit beoordelingspunt gekoppeld.", auditTrail: "Controlespoor ({count})", actorVia: "{actor} via {source}", unknownSource: "onbekende bron", noAuditEvents: "Er zijn geen controlegebeurtenissen aan deze entiteit gekoppeld.",
    reviewPlanCreated: "Beoordeling vastgelegd en wisplan #{id} aangemaakt", reviewItemUpdated: "Beoordelingspunt bijgewerkt", cleanupFinished: "Externe opschoning voltooid met status {status}", manualCleanupRecorded: "Handmatig bewijs voor provideropschoning vastgelegd", databaseErasureCompleted: "Databasewissing transactioneel voltooid",
    application: "Sollicitatie", success_fee: "Succesvergoeding", verification: "Verificatie",
    feeStatusUpdated: "Status van vergoeding bijgewerkt", verificationApproved: "Verificatie goedgekeurd", verificationRejected: "Verificatie afgewezen", legalEscalationRecorded: "Account gemarkeerd voor juridische escalatie", noteAdded: "Notitie toegevoegd", userReinstated: "Gebruiker hersteld", invalidDownloadUrl: "De download-URL voor verificatie is ongeldig.", downloadFailed: "Het verificatiedocument kon niet worden geopend",
    active: "Actief", pending_verification: "Openstaande verificatie", suspended: "Opgeschort", disputed: "Betwist", ended: "Beeindigd", paused: "Gepauzeerd", pending: "Openstaand", approved: "Goedgekeurd", rejected: "Afgewezen", paid: "Betaald", failed: "Mislukt", open: "Open", in_progress: "In behandeling", resolved: "Opgelost", dismissed: "Afgewezen", low: "Laag", medium: "Gemiddeld", high: "Hoog", critical: "Kritiek", initial: "Initieel", other: "Overig", review: "Beoordelen", application_review: "Sollicitatiebeoordeling", submission_evidence: "Indieningsbewijs", employer_response: "Werkgeversreactie", offer_attribution: "Herkomst van aanbod", verification_overdue: "Verificatie te laat", payment_failed: "Betaling mislukt", legal_escalation: "Juridische escalatie", employment_ended: "Dienstverband beeindigd", privacy_deletion: "Privacyverwijdering", scrub_and_retain: "Opschonen en bewaren", retain: "Bewaren", provider_revoke: "Providertoegang intrekken", object_delete: "Object verwijderen", private_object_delete: "Priveobject verwijderen", retention_hold: "Bewaarplicht", database_finalize: "Databasewissing afronden", prepare: "Voorbereiding", manual_confirmation: "Handmatige bevestiging", external_handoff: "Externe overdracht", planned: "Gepland", cleanup_in_progress: "Opschoning actief", blocked: "Geblokkeerd", ready_for_database: "Gereed voor database", completed: "Voltooid",
  },
} as const satisfies Record<SupportedLocale, Record<string, string>>;

export type AdminFinancialCopyKey = keyof typeof copy.en;

export function getAdminFinancialCopy(locale: SupportedLocale, key: AdminFinancialCopyKey) {
  return copy[locale][key];
}

export function formatAdminFinancialCopy(locale: SupportedLocale, key: AdminFinancialCopyKey, values: Record<string, string | number>) {
  return Object.entries(values).reduce((result, [name, value]) => result.replaceAll(`{${name}}`, String(value)), getAdminFinancialCopy(locale, key) as string);
}

export function getAdminFinancialStatusCopy(locale: SupportedLocale, status: string) {
  return status in copy.en ? copy[locale][status as AdminFinancialCopyKey] : status.replaceAll("_", " ");
}
