import type { SupportedLocale } from "@shared/localization";

export const landingCopy = {
  en: {
    tagline: "Job hunting done right.", heroTitle: "Your job search, under control.", heroDescription: "Discover roles from configured sources, build tailored materials, and keep applications, follow-ups, and responses in one reviewable operating ledger.", goToDashboard: "Go to dashboard", buildWorkspace: "Build your search workspace", seeHowItWorks: "See how it works", approvalBoundary: "External applications and follow-ups stay behind explicit approval and confirmation steps.",
    operatingModel: "Operating model", operatingModelTitle: "Prepare, review, and record every next step.", versionedEvidence: "Versioned candidate evidence", versionedEvidenceDetail: "Resume versions and profile data remain attributable to each prepared application.", sourceAwareDiscovery: "Source-aware job discovery", sourceAwareDiscoveryDetail: "Configured supported sources feed normalized listings and duplicate relationships.", reviewGatedExecution: "Review-gated execution", reviewGatedExecutionDetail: "Hire.AI prepares decisions and drafts; users confirm consequential external actions.",
    accountableTitle: "Designed for accountable job searching", accountableDescription: "The system records why work was prepared and what still needs your decision.", evidenceBeforeAction: "Evidence before action", evidenceBeforeActionDetail: "Prepared applications retain the resume version, profile snapshot, decision rationale, and review state used to create them.", externalControl: "Control at external boundaries", externalControlDetail: "Application submission and follow-up delivery require explicit approval and a confirmed handoff. The ledger does not invent submission evidence.", oneRecord: "One operating record", oneRecordDetail: "Responses, interviews, offers, follow-ups, and compliance work are connected to the originating application for clear next actions.",
    howItWorks: "How it works", howItWorksDescription: "A controlled workflow from candidate evidence to external handoff", importEvidence: "Import candidate evidence", importEvidenceDetail: "Import a resume version, then review the skills, history, and preferences that inform future application preparation.", scanSources: "Scan configured sources", scanSourcesDetail: "Choose from the supported sources available to your workspace. Hire.AI normalizes listings and keeps duplicate relationships visible.", reviewWork: "Review prepared work", reviewWorkDetail: "Review matches, materials, follow-up drafts, and evidence before confirming a consequential external handoff.",
    faqTitle: "Frequently asked questions", faqDescription: "Everything you need to know about how Hire.AI works", faqApplicationsQuestion: "How does Hire.AI handle applications?", faqApplicationsAnswer: "Hire.AI prepares match decisions and application materials from your profile evidence. External application submission remains a separate, review-gated handoff that you explicitly approve and confirm.", faqSecurityQuestion: "Is my data safe and secure?", faqSecurityAnswer: "Resume versions and application evidence are tracked so you can see what was used. External inbox and cloud connectors remain unavailable until explicit provider authorization is completed. Do not treat the current prototype as a finished production data-processing service.", faqAutomationQuestion: "Will employers know I'm using an automated service?", faqAutomationAnswer: "Hire.AI does not silently submit applications. You control the external handoff through the intended employer channel after reviewing the prepared materials.",
    faqVolumeQuestion: "How many applications can Hire.AI prepare per day?", faqVolumeAnswer: "You control the daily preparation limit. Hire.AI prioritizes high-fit roles and adds them to a review queue before any final submission.", faqPlatformsQuestion: "What job platforms do you support?", faqPlatformsAnswer: "We aggregate opportunities from supported sources and prepare review workflows for common ATS platforms such as Greenhouse and Lever. Final submission remains under your control.", faqReviewQuestion: "Can I review applications before they're sent?", faqReviewAnswer: "Yes. Every prepared application remains in a review queue until you verify the details and submit it.", ctaTitle: "Ready to run your job search from one place?", ctaDescription: "Build a traceable workflow for job discovery, preparation, approvals, and follow-up.", ctaHint: "Set up your profile evidence and job-search policy before preparing work.", mission: "On a mission to reduce worldwide unemployment", copyright: "© 2026 Hire.AI. All rights reserved.", terms: "Terms of service",
  },
  nl: {
    tagline: "Goed en beheerst op zoek naar werk.", heroTitle: "Je zoektocht naar werk, onder controle.", heroDescription: "Vind functies via ingestelde bronnen, bouw afgestemde materialen en beheer sollicitaties, opvolgingen en reacties in één controleerbaar werkregister.", goToDashboard: "Naar overzicht", buildWorkspace: "Bouw je zoekwerkruimte", seeHowItWorks: "Bekijk hoe het werkt", approvalBoundary: "Externe sollicitaties en opvolgingen blijven achter expliciete goedkeurings- en bevestigingsstappen.",
    operatingModel: "Werkmodel", operatingModelTitle: "Bereid elke volgende stap voor, beoordeel en leg vast.", versionedEvidence: "Versiebeheerd kandidaatbewijs", versionedEvidenceDetail: "Cv-versies en profielgegevens blijven herleidbaar tot elke voorbereide sollicitatie.", sourceAwareDiscovery: "Bronbewuste vacatureverkenning", sourceAwareDiscoveryDetail: "Ingestelde ondersteunde bronnen leveren genormaliseerde vacatures en zichtbare duplicaatrelaties.", reviewGatedExecution: "Uitvoering na beoordeling", reviewGatedExecutionDetail: "Hire.AI bereidt besluiten en concepten voor; gebruikers bevestigen belangrijke externe acties.",
    accountableTitle: "Ontworpen voor een verantwoordelijke zoektocht naar werk", accountableDescription: "Het systeem legt vast waarom werk is voorbereid en wat nog op jouw besluit wacht.", evidenceBeforeAction: "Bewijs vóór actie", evidenceBeforeActionDetail: "Voorbereide sollicitaties bewaren de gebruikte cv-versie, profielmomentopname, beslisreden en beoordelingsstatus.", externalControl: "Controle bij externe grenzen", externalControlDetail: "Indiening en verzending van opvolging vereisen expliciete goedkeuring en een bevestigde overdracht. Het register verzint geen indieningsbewijs.", oneRecord: "Eén werkregister", oneRecordDetail: "Reacties, gesprekken, aanbiedingen, opvolgingen en nalevingswerk blijven gekoppeld aan de oorspronkelijke sollicitatie voor duidelijke vervolgstappen.",
    howItWorks: "Hoe het werkt", howItWorksDescription: "Een beheerst proces van kandidaatbewijs tot externe overdracht", importEvidence: "Kandidaatbewijs importeren", importEvidenceDetail: "Importeer een cv-versie en beoordeel daarna de vaardigheden, geschiedenis en voorkeuren die toekomstige sollicitatievoorbereiding sturen.", scanSources: "Ingestelde bronnen scannen", scanSourcesDetail: "Kies uit de ondersteunde bronnen in je werkruimte. Hire.AI normaliseert vacatures en houdt duplicaatrelaties zichtbaar.", reviewWork: "Voorbereid werk beoordelen", reviewWorkDetail: "Beoordeel matches, materialen, opvolgconcepten en bewijs voordat je een belangrijke externe overdracht bevestigt.",
    faqTitle: "Veelgestelde vragen", faqDescription: "Alles wat je moet weten over hoe Hire.AI werkt", faqApplicationsQuestion: "Hoe verwerkt Hire.AI sollicitaties?", faqApplicationsAnswer: "Hire.AI bereidt matchbesluiten en sollicitatiematerialen voor op basis van je profielbewijs. Externe indiening blijft een afzonderlijke, beoordelingsplichtige overdracht die je expliciet goedkeurt en bevestigt.", faqSecurityQuestion: "Zijn mijn gegevens veilig?", faqSecurityAnswer: "Cv-versies en sollicitatiebewijs worden bijgehouden zodat je ziet wat is gebruikt. Externe inbox- en cloudkoppelingen blijven onbeschikbaar totdat expliciete providerautorisatie is afgerond. Behandel het huidige prototype niet als een voltooide productiedienst voor gegevensverwerking.", faqAutomationQuestion: "Weten werkgevers dat ik een geautomatiseerde dienst gebruik?", faqAutomationAnswer: "Hire.AI dient sollicitaties niet stil in. Jij beheert de externe overdracht via het bedoelde werkgeverskanaal nadat je de voorbereide materialen hebt beoordeeld.",
    faqVolumeQuestion: "Hoeveel sollicitaties kan Hire.AI per dag voorbereiden?", faqVolumeAnswer: "Jij bepaalt de dagelijkse voorbereidingslimiet. Hire.AI geeft prioriteit aan goed passende functies en voegt ze vóór definitieve indiening toe aan een beoordelingswachtrij.", faqPlatformsQuestion: "Welke vacatureplatforms ondersteunen jullie?", faqPlatformsAnswer: "We verzamelen kansen uit ondersteunde bronnen en bereiden beoordelingsprocessen voor gangbare ATS-platforms zoals Greenhouse en Lever voor. Definitieve indiening blijft onder jouw controle.", faqReviewQuestion: "Kan ik sollicitaties beoordelen voordat ze worden verzonden?", faqReviewAnswer: "Ja. Elke voorbereide sollicitatie blijft in een beoordelingswachtrij totdat je de details controleert en deze indient.", ctaTitle: "Klaar om je zoektocht naar werk vanuit één plek te beheren?", ctaDescription: "Bouw een herleidbaar proces voor vacatureverkenning, voorbereiding, goedkeuringen en opvolging.", ctaHint: "Stel je profielbewijs en zoekbeleid in voordat je werk voorbereidt.", mission: "Met de missie om wereldwijde werkloosheid te verminderen", copyright: "© 2026 Hire.AI. Alle rechten voorbehouden.", terms: "Servicevoorwaarden",
  },
} as const satisfies Record<SupportedLocale, Record<string, string>>;

export type LandingCopyKey = keyof typeof landingCopy.en;

export function getLandingCopy(locale: SupportedLocale, key: LandingCopyKey) {
  return landingCopy[locale][key];
}
